server:
  port: ${PORT:8761}

spring:
  application:
    name: service-discovery

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    renewalPercentThreshold: 0.49

logging:
  level:
    com.netflix.eureka: ON
    com.netflix.discovery: ON